# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: "3.4"

services:
  topics-api:
    image: backend
    build:
      context: backend
      dockerfile: ./Dockerfile
    ports:
      - 6000:5000

  frontend:
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:3000

  some-mongo:
    image: mongo
    restart: always
    volumes:
      - db_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty123
    ports:
      - 27017:27017
volumes:
  db_data:
networks:
  lemoncode-challenge:
