apiVersion: v1
kind: Pod
metadata:
  name: wp
  labels:
    app: wp
spec:
  containers:
    - name: wp
      image: wordpress:5.8.1
      ports:
        - containerPort: 80
      env:
        - name: WORDPRESS_DB_HOST
          value: mysql
        - name: WORDPRESS_DB_USER
          value: eduwp
        - name: WORDPRESS_DB_PASSWORD
          value: Passw0rd!
        - name: WORDPRESS_DB_NAME
          value: wpdata
